# Generated by Django 4.2.11 on 2024-04-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(default='Sem One', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Year_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('no_of_students', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='allocator.course')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Table_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='allocator.time_table')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=100)),
                ('end_time', models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='allocator.year_course')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='allocator.time_table_day')),
            ],
        ),
    ]
