# Generated by Django 4.2.11 on 2024-04-30 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0002_time_table_year_course_time_table_day_lecture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year_course',
            name='lecturer',
        ),
    ]
