# Generated by Django 4.2.11 on 2024-04-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0003_remove_year_course_lecturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='study_topic',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
