# Generated by Django 4.2.11 on 2024-04-30 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0004_lecture_lecturer_lecture_study_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Timetable_Lecture_Timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=100)),
                ('end_time', models.CharField(choices=[('8:00am', '8:00am'), ('9:00am', '9:00am'), ('10:00am', '10:00am'), ('11:00am', '11:00am'), ('12:00pm', '12:00pm'), ('1:00pm', '1:00pm'), ('2:00pm', '2:00pm'), ('3:00pm', '3:00pm'), ('4:00pm', '4:00pm'), ('5:00pm', '5:00pm'), ('6:00pm', '6:00pm')], max_length=100)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timings', to='allocator.time_table')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='allocator.timetable_lecture_timing'),
        ),
    ]
