# Generated by Django 4.2.11 on 2024-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0005_remove_lecture_end_time_remove_lecture_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='state',
            field=models.CharField(choices=[('In Use', 'In Use'), ('Free', 'Free'), ('Closed', 'Closed')], default='Free', max_length=100),
        ),
    ]
