# Generated by Django 4.2.11 on 2024-05-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocator', '0008_alter_course_course_type_alter_room_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allocated_to',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='from_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='to_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
